### ISSUE TITLE
Bug Cant run

### ISSUE THREAD

**Issue by py7hon** [odrling/Aegisub#4]
OS: ArchLinux 5.6.15-arch1-1

```terminal
[root@moe ~]# aegisub
18:24:41: Warning: Mismatch between the program and library build versions detected.
The library used 3.0 (wchar_t,compiler with C++ ABI 1013,wx containers,compatible with 2.8),
and your program used 3.0 (wchar_t,compiler with C++ ABI 1014,wx containers,compatible with 2.8).

```

**Comment by odrling** [comment]
Hi,
It looks like you upgraded your system and wxWidget was built with a newer C++ toolchain.
I believe this issue will go away if you rebuild the package from the AUR.

**Comment by py7hon** [comment]
but i have a same problem after rebuilding

**Comment by pjeanjean** [comment]
I also see this warning on Arch, but it can be safely ignored.
Are you sure you don't have any other output?

**Comment by py7hon** [comment]
> Are you sure you don't have any other output?

The Output as same

**Comment by odrling** [comment]
I found this bug that sounds similar (at least in how it doesn't log anything for crashing aegisub at startup) https://github.com/Aegisub/Aegisub/issues/185
Can you try running this command: 
```env LC_TIME=en_US.UTF-8 GDK_BACKEND=x11 aegisub```

**Comment by pjeanjean** [comment]
We are not able to reproduce your issue :/

Maybe you should give us more details about your environment (DE/WM/Sound setup).
Your Arch is not up to date, so you could also start by updating your system.
And what about the package `aegisub-git`, does it have the same issue? Might be worth testing.

**Comment by py7hon** [comment]
> I found this bug that sounds similar (at least in how it doesn't log anything for crashing aegisub at startup) [Aegisub/Aegisub#185](https://github.com/Aegisub/Aegisub/issues/185)
> Can you try running this command:
> `env LC_TIME=en_US.UTF-8 GDK_BACKEND=x11 aegisub`

same cant run or open
[Video](https://files.catbox.moe/rgdtvn.mp4)





> We are not able to reproduce your issue :/
> 
> Maybe you should give us more details about your environment (DE/WM/Sound setup).

I use DWM with PulseAudio
> Your Arch is not up to date, so you could also start by updating your system.

this fresh arch install
> And what about the package `aegisub-git`, does it have the same issue? Might be worth testing.

yeah same

**Comment by odrling** [comment]
What does `locale -a` return ?

**Comment by py7hon** [comment]
> What does `locale -a` return ?

```
[root@moe dwm]# locale -a
C
POSIX
en_US.utf8
```

**Comment by odrling** [comment]
well I would try `env LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8 aegisub` I don't really see what else could go wrong in your setup
Edit: added `LANG`, better safe than sorry

**Comment by odrling** [comment]
@py7hon did you get it to work ?

**Comment by py7hon** [comment]
> @py7hon did you get it to work ?

now is working, but use the aur is not working
